#BNF+IAT 1.0 UTF-8;
!grammar rainbow;
!slot <forward>;
!slot <back>;
!slot <shot>;
!slot <hidePanel>;
!slot <showPanel>;
!slot <showPic>;
!slot <startNav>;
!slot <playVideo>;
!slot <replayVideo>;
!slot <ok>;
!slot <cancel>;
!slot <send>;
!slot <playAnim>;
!slot <restartNav>;
!slot <checkMail>;
!slot <preMail>;
!slot <nextMail>;
!slot <detailMail>;
!slot <closeMail>;
!slot <deleteMail>;
!slot <lockPanel>;
!slot <movePanel>;
!slot <skipPresentation>;
!slot <lockModel>;
!slot <moveModel>;
!slot <skipNav>;
!start <callStart>;
<callStart>:<forward>|<shot>|<back>|<hidePanel>|<showPanel>|<showPic>|<startNav>|<playVideo>|<replayVideo>|<ok>|<cancel>|<send>|<playAnim>|<restartNav>|<checkMail>|<preMail>|<nextMail>|<detailMail>|<closeMail>|<deleteMail>|<lockPanel>|<movePanel>|<movePanel>|<skipPresentation>|<lockModel>|<moveModel>|<skipNav>;
<forward>:前一步;
<back>:后一步;
<shot>:开启拍照;
<hidePanel>:隐藏面板;
<showPanel>:显示面板;
<showPic>:显示图片;
<startNav>:开始引路;
<playVideo>:播放视频;
<replayVideo>:重新播放;
<ok>:确定;
<cancel>:取消;
<send>:发送;
<playAnim>:播放动画;
<restartNav>:重新引导;
<checkMail>:查看邮件;
<preMail>:前一封;
<nextMail>:后一封;
<detailMail>:查看详情;
<closeMail>:关闭;
<deleteMail>:删除邮件;
<lockPanel>:固定面板;
<movePanel>:移动面板;
<skipPresentation>:跳过展示;
<lockModel>:固定模型;
<moveModel>:移动模型;
<skipNav>:跳过引路;